# Generated by Django 4.2.1 on 2023-06-05 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('part', models.CharField(choices=[('M', 'Morning'), ('N', 'Noon'), ('E', 'Evening')], default='M', max_length=1)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.skill')),
            ],
        ),
    ]
