# Generated by Django 4.2.1 on 2023-06-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='skill',
            name='equipments',
            field=models.ManyToManyField(to='main_app.equipment'),
        ),
    ]
